=== badzim/VoyageurDeSante/src/xsd/cabinet.xsd
<?xml version="1.0"?>

<!--
    Document   : cabinet.xsl
    Created on : 20 novembre 2023, 13:45
    Author     : Rahmani Imen & Badzi Amine
    Description: Ce fichier corespond au xsd du cabinet
        
-->

<xs:schema version="1.0"
            targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
            xmlns:vs="http://www.ujf-grenoble.fr/l3miage/medical"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
            
    
    <!--Définition de l'élément "cabinet"-->
    <xs:element name="cabinet" type="vs:Cabinet"/>

    <!--Définition du type "Cabinet"-->
    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="adresse" type="vs:AdresseCabinet"/>
            <xs:element name="infirmiers" type="vs:Infirmiers"/>
            <xs:element name="patients" type="vs:Patients"/>
        </xs:sequence>

    </xs:complexType>
    
    <!-- Definition du type AdresseCabinet -->
    <xs:complexType name="AdresseCabinet">
        <xs:sequence>
            <xs:element name="numéro" type="xs:int" minOccurs="0"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="codePostal" type="vs:CodePostal"/>
            <xs:element name="ville" type="xs:string"/>
        </xs:sequence>

    </xs:complexType>

    <!-- Définition du type "CodePostal" -->
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    




    <!-- Definition du type Infirmiers -->

    <xs:complexType name="Infirmiers">
        
        <xs:sequence>
            <xs:element name="infirmier" type="vs:Infirmier"  maxOccurs="unbounded"/>
        </xs:sequence>

    </xs:complexType>




    <!-- Définition du type "Infirmier" -->
    <xs:complexType name="Infirmier">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="photo" type="vs:Photo"/>
        </xs:sequence>
        <!-- Contrainte sur l'attribut "id"-->
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>




    <!--Définition du type "photo"-->
    <xs:simpleType name="Photo">
            <!-- Contrainte sur le format du nom de fichier pour la photo -->
            <xs:restriction base="xs:string">
                <xs:pattern value=".*\.(png|jpg|jpeg)"/>
            </xs:restriction>

    </xs:simpleType>

   
    
    
    

    <!-- Definition du type "Patients" -->
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="vs:Patient" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    
    
    
    <!-- Definition du type "Patient" -->
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="vs:Nom"/>
            <xs:element name="prenom" type="vs:Prenom"/>
            <xs:element name="sexe" type="vs:Sexe"/>
            <xs:element name="naissance" type="xs:date"/>
            <xs:element name="numero" type="xs:string"/>
            <xs:element name="adresse" type="vs:AdressePatient"/>
            <xs:element name="visite" type="vs:Visite" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>



    <!-- Définition du type "Nom" -->
    <xs:simpleType name="Nom">
        <!-- Contrainte sur la longueur du nom -->
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
    
    <!-- Définition du type "Prenom" -->
    <xs:simpleType name="Prenom">
        <!-- Contrainte sur la longueur du prénom -->
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>



     <!-- Définition du type "Sexe" -->
    <xs:simpleType name="Sexe">
        <!-- Contrainte sur les valeurs possibles du sexe -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
     </xs:simpleType>
     
     
     
     <!-- Définition du type "AdressePatient" -->
     <xs:complexType name="AdressePatient">
        <xs:sequence>
            <xs:element name="étage" type="xs:int" minOccurs="1"/>
            <xs:element name="numéro" type="xs:int" minOccurs="0"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="ville" type="xs:string"/>
            <xs:element name="codePostal" type="vs:CodePostal"/>
        </xs:sequence>

    </xs:complexType>
    
    
     <!-- Définition du type "Visite" -->
     <xs:complexType name="Visite">
         <xs:sequence>
             <xs:element name="acte" type="vs:Acte" maxOccurs="unbounded"/>
         </xs:sequence>
         <!-- Attribut obligatoire pour une visite -->
         <xs:attribute name="date" type="xs:date" use="required"/>
         <xs:attribute name="intervenant" type="xs:string"/>
     </xs:complexType>
     

     <!-- Définition du type "Acte" -->
     <xs:complexType name="Acte">
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    

    
    
</xs:schema>

=== badzim/VoyageurDeSante/src/xml/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->


<vs:cabinet xmlns:vs="http://www.ujf-grenoble.fr/l3miage/medical"
            xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.ujf-grenoble.fr/l3miage/medical ../xsd/cabinet.xsd">
    <vs:nom>Soins à Grenbole</vs:nom>
    <vs:adresse>
        <vs:numéro>60</vs:numéro>
        <vs:rue>rue de la chimie</vs:rue>
        <vs:codePostal>38041</vs:codePostal>
        <vs:ville>Grenoble
        </vs:ville>
    </vs:adresse>

    <vs:infirmiers>
        
        
        <vs:infirmier id="001">
            <vs:nom>Fréchie</vs:nom>
            <vs:prenom>Sarah</vs:prenom>
            <vs:photo>sarah.png</vs:photo>
        </vs:infirmier>
        
        
        <vs:infirmier id="002">
            <vs:nom>Stické</vs:nom>
            <vs:prenom>Sophie</vs:prenom>
            <vs:photo>sophie.png</vs:photo>
        </vs:infirmier>
        
        
        <vs:infirmier id="003">
            <vs:nom>Ochon</vs:nom>
            <vs:prenom>Paul</vs:prenom>
            <vs:photo>paul.png</vs:photo>
        </vs:infirmier>
        
        
    </vs:infirmiers>

    <vs:patients>
        
        
        <vs:patient>
            <vs:nom>Alécole</vs:nom>
            <vs:prenom>Yvon</vs:prenom>
            <vs:sexe>M</vs:sexe>
            <vs:naissance>1998-08-22</vs:naissance>
            <vs:numero>198082205545852</vs:numero>
            <vs:adresse>
                <vs:étage>6
                </vs:étage>
                <vs:numéro>50</vs:numéro>
                <vs:rue>avenue Felixe Viallet</vs:rue>
                <vs:ville>Grenoble</vs:ville>
                <vs:codePostal>38031</vs:codePostal>
            </vs:adresse>
      
                <vs:visite date="2015-12-08" intervenant="001">
                    
                        <vs:acte id="109"/>
         
                </vs:visite>

        </vs:patient>
        
        
        
        <vs:patient>
            <vs:nom>Orouge</vs:nom>
            <vs:prenom>Elvire</vs:prenom>
            <vs:sexe>F</vs:sexe>
            <vs:naissance>1982-03-08</vs:naissance>
            <vs:numero>2820338235251</vs:numero>
            <vs:adresse>
                <vs:étage>1</vs:étage>
                <vs:numéro>2</vs:numéro>
                <vs:rue>Rond-Point de la Croix de Vie</vs:rue>
                <vs:ville>La Tronche</vs:ville>
                <vs:codePostal>38700</vs:codePostal>
            </vs:adresse>
      
                <vs:visite date="2015-12-08">
                    
                        <vs:acte id="300"></vs:acte>
            
                </vs:visite>
          

        </vs:patient>
        
        
        
        
        <vs:patient>
            <vs:nom>Pien</vs:nom>
            <vs:prenom>Oscare</vs:prenom>
            <vs:sexe>M</vs:sexe>
            <vs:naissance>1975-03-25</vs:naissance>
            <vs:numero>17503386569264
            </vs:numero>
            <vs:adresse>
                <vs:étage>2</vs:étage>
                <vs:numéro>3</vs:numéro>
                <vs:rue>rue Casimir Brenier</vs:rue>
                <vs:ville>Grenoble</vs:ville>
                <vs:codePostal>38000</vs:codePostal>
            </vs:adresse>
           
                <vs:visite date="2015-12-08">
            
                        <vs:acte id="104"></vs:acte>
                        <vs:acte id="101"></vs:acte>
                    
                
                </vs:visite>

        </vs:patient>
        
        
        
        <vs:patient>
            <vs:nom>Kapoëtla</vs:nom>
            <vs:prenom>Xavier</vs:prenom>
            <vs:sexe>M</vs:sexe>
            <vs:naissance>2011-08-02</vs:naissance>
            <vs:numero>1110838633571</vs:numero>
            <vs:adresse>
                <vs:étage>2</vs:étage>
                <vs:numéro>25</vs:numéro>
                <vs:rue>rue des Martyrs</vs:rue>
                <vs:ville>Grenoble</vs:ville>
                <vs:codePostal>38042</vs:codePostal>
            </vs:adresse>
            
            
                <vs:visite date="2015-12-08">
              
                        <vs:acte id="111"></vs:acte>
    
                </vs:visite>
                
               

        </vs:patient>

    </vs:patients>


</vs:cabinet>
